apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid19-deployment
  labels:
    app: vuejs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vuejs
  template:
    metadata:
      labels:
        app: vuejs
    spec:
      containers:
        - name: covid19-frontend
          image: denisduev/covid-19-vuejs:latest
          ports:
            - containerPort: 8080
          env:
            - name: VUE_APP_EXTERNAL_NEWS_API_KEY # The name of env variable
              valueFrom:
                secretKeyRef:
                  name: news-api-token # The name of the secret
                  key: api-token # The name of the variable stored in the secret
---
apiVersion: v1
kind: Service
metadata:
  name: covid19-service-frontend
spec:
  selector:
    app: vuejs
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: news-api-token
type: Opaque
stringData:
  api-token: <token-here>